[tool.briefcase]
project_name = "Multi app"
bundle = "com.bestcode"
version = "0.0.1"
url = "https://bestcode.com/multi-app"
license = "BSD license"
author = 'Christian Erhijotah'
author_email = "Christianerhijotah@gmail.com"

[tool.briefcase.app.multi-app]
formal_name = "Multi app"
description = "An an that does a bunch of cool stuffs"
icon = "src/multi_app/resources/multi-app"
sources = ['src/multi_app']
requires = [
]


[tool.briefcase.app.multi-app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.multi-app.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.multi-app.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.multi-app.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.multi-app.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.multi-app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.multi-app.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.multi-app.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
